server:
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://end-digits-postgres-db:5432/end-digits-db
    username: postgres
    password: mysecretpassword
  change-log: classpath:/db/db.changelog-master.yaml

end-digits-fetcher:
  local-file: sverigesradio.html

basic-auth:
  users:
    - username: user
      password: password
      role: USER
    - username: admin
      password: admin
      role: ADMIN