server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://10.30.80.3:5432/end-digits-db
    username: postgres
    password: ${DBPASS}
  change-log: classpath:/db/db.changelog-master.yaml

end-digits-fetcher:
  url: https://sverigesradio.se/ringsaspelarvi

basic-auth:
  users:
    - username: user
      password: ${USERPASS}
      role: USER
    - username: admin
      password: ${ADMINPASS}
      role: ADMIN