name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE: end-digits-fetcher
  SERVICE_NAME: end-digits-fetcher
  REGION: europe-north1
  HOST: eu.gcr.io
  CONTAINER_REGISTRY_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}
  CLOUD_RUN_ACCOUNT_KEY: ${{ secrets.GCP_CLOUD_RUN_SA_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build project
        run: make build

      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs

  build-and-publish-docker:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        with:
          service_account_key: ${{ env.CONTAINER_REGISTRY_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - run: |-
          gcloud --quiet auth configure-docker

      - name: Download jar
        uses: actions/download-artifact@v2
        with:
          name: Package

      - name: Build docker image
        run: |
          mkdir -p build/dependency && (cd build/dependency; jar -xf ../../*.jar)
          docker build \
            --tag "$HOST/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
            .

      - name: Publish docker image to GCR
        run: |
          docker push "$HOST/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-publish-docker
    steps:

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        with:
          service_account_key: ${{ env.CLOUD_RUN_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}


      - name: Deploy
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --image "$HOST/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
            --region "$REGION" \\
            --set-env-vars [SPRING_PROFILES_ACTIVE=live] \
            --platform "managed" \
            --allow-unauthenticated
