name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE: end-digits-fetcher
  HOST: eu.gcr.io
  CONTAINER_REGISTRY_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}
  COMPUTE_ENGINE_ACCOUNT_KEY: ${{ secrets.GCP_COMPUTE_ENGINE_SA_KEY }}
  GCE_INSTANCE: jag-vill-ringa-instance
  GCE_INSTANCE_ZONE: europe-north1-a
  DB_PASSWORD: $ {{ secrets.DB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build project
        run: make build

      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs

  build-and-publish-docker:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ env.CONTAINER_REGISTRY_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Gcloud configer docker
        run: |-
          gcloud --quiet auth configure-docker

      - name: Download jar
        uses: actions/download-artifact@v2
        with:
          name: Package

      - name: Build docker image
        run: |
          mkdir -p build/dependency && (cd build/dependency; jar -xf ../../*.jar)
          docker build \
            --tag "$HOST/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
            .

      - name: Publish docker image to GCR
        run: |
          docker push "$HOST/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-publish-docker
    steps:

      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ env.COMPUTE_ENGINE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Deploy
        run: |-
          gcloud compute instances update-container "$GCE_INSTANCE" \
            --zone "$GCE_INSTANCE_ZONE" \
            --container-image "$HOST/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
            --container DBPASS=${{ env.DB_PASSWORD }}
